---
kind: pipeline
type: docker
name: appsights-elk

steps:
- name: elasticsearch image build
  image: plugins/docker
  settings:
    repo: mbern/elastic-supp
    auto_tag: true
    dockerfile: elasticsearch/Dockerfile
    context: ./elasticsearch
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
- name: filebeat image build
  image: plugins/docker
  settings:
    repo: mbern/filebeat-supp
    auto_tag: true
    dockerfile: filebeat/Dockerfile
    context: ./filebeat
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASS
  


trigger:
  event:
  - push
  - tag