---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"

# Local Docker
#elasticsearch.url: "http://elasticsearch:9200"

# KITT
#elasticsearch.url: http://localhost:9200